name: Release
on: 
  release:
         types: ['published']

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0.3.0
        with:
          image: yewnorosen/rkvst-sbom:latest
          format: cyclonedx
          
  publish-sbom:
    name: Publish SBOM to RKVST
    runs-on: ubuntu-latest
    steps:
       - uses: actions/download-artifact@v2
       - uses: leflambeur/rkvst-sbom@v0.0.2d
         env:
           CLIENT_ID: ${{ secrets.QUINT_CLIENT_ID }}
           CLIENT_SECRET: ${{ secrets.QUINT_CLIENT_SECRET }}
         with:
           command: release
           asset_id: assets/9900e40a-bd9f-41f8-a678-be0b5556b365
           attachments: '["yewnorosen-rkvst-sbom_latest.cyclonedx/yewnorosen-rkvst-sbom_latest.cyclonedx"]'
